apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${PROMETHEUS_HOST}:${PROMETHEUS_PORT}
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://${LOKI_HOST}:${LOKI_PORT}
    editable: true
    jsonData:
      maxLines: 1000
